#!/usr/bin/env bash

# Usage: ./0-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain_information () {
    subdomain="$1"
    domain="$2"
    dig_result=$(dig "$subdomain.$domain")
    record_type=$(echo "$dig_result" | awk '/IN\sA/ {print $4}')
    destination=$(echo "$dig_result" | awk '/IN\sA/ {print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ "$#" == 1 ]
then
    domain="$1"
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"
    do
        domain_information "$subdomain" "$domain"
    done
elif [ "$#" == 2 ]
then
    domain_information "$2" "$1"
fi
